# Supabase project configuration
project_id = "btmrckamcwtaimbpfqfu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[edge_runtime]
enabled = true

[db]
port = 54322
shadow_port = 54320
