name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_s4xjBcQIdTKUhPwaIgXFaqBX
          vercel-project-id: prj_ZeBmkrzWUXvclCjCk1xbLAsP2Tch
          working-directory: ./auto-web-ui
